name: Streamlit Keep Alive

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $ cd Stream_app_model_demo
          pip install -r requirements.txt

      - name: Keep Alive
        run: |
          curl --request GET --url https://freshwater-quality.streamlit.app/
