name: Streamlit Keep Alive

on:
  schedule:
    - cron: "*/600 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r https://github.com/hariprasath-v/Intel_oneAPI_Hackerearth_Predict-the-quality-of-freshwater/blob/main/Stream_app_model_demo/freshwater_quality_prediction_app.py

      - name: Keep Alive
        run: |
          curl --request GET --url https://freshwater-quality.streamlit.app/
