name: Streamlit Keep Alive

on:
  schedule:
    - cron: "*/600 * * * *"

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          $ cd Intel_oneAPI_Hackerearth_Predict-the-quality-of-freshwater/Stream_app_model_demo
          pip3 install -r requirements.txt

      - name: Keep Alive
        run: |
          curl --request GET --url https://freshwater-quality.streamlit.app/
